trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**.pbix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PowerBIActions@5
  inputs:
    PowerBIServiceEndpoint: 'Power BI Service Connection'
    Action: 'Publish'
    WorkspaceName: 'Dev'
    PowerBIPath: '$(System.DefaultWorkingDirectory)/_NastassiaLahoiskaya.Pet_project (5)/drop/pet_project.pbix'

