trigger:
- push

pool:
  vmImage: windows-latest

stages:
- stage: FirstStage
  jobs:
  - job: copyfile
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**.pbix'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: TestStage
  jobs:
  - job: DeployToTest
    variables:
      PipelineName: 'Demo'
      UserEmail: 'anastasia.lahoiskaya@gmail.com'
      WorkspaceName: 'DEVELOPMENT'
    steps:
    - task: DeploymentPipelines-Deploy@1
      inputs:
        pbiConnection: 'Power BI'
        pipeline: '$(PipelineName)'
        stageOrder: 'Test'
        deployType: 'All'
        waitForCompletion: true
        createNewWS: true
        newWsName: '$(WorkspaceName)'
        allowCreateArtifact: true
        allowOverwriteArtifact: true
        updateApp: false
        allowOverwriteTargetArtifactLabel: false
        allowPurgeData: false
        allowSkipTilesWithMissingPrerequisites: false
        allowTakeOver: false

  - job: AddUserToWorkspaceTest
    steps:
    - task: Workspaces-AddUser@1
      inputs:
        pbiConnection: 'Power BI'
        workspace: '$(WorkspaceName)'
        userUpn: '$(UserEmail)'
        permission: 'Admin'

- stage: ProductionStage
  jobs:
  - job: DeployContentToProduction
    variables:
      PipelineName: 'Demo'
      UserEmail: 'anastasia.lahoiskaya@gmail.com'
      WorkspaceName: 'DEVELOPMENT'
    steps:
    - task: DeploymentPipelines-Deploy@1
      inputs:
        pbiConnection: 'Power BI'
        pipeline: '$(PipelineName)'
        stageOrder: 'Production'
        waitForCompletion: true
        deployType: 'All'
        createNewWS: true
        allowCreateArtifact: true
        allowOverwriteArtifact: true
        updateApp: false
        allowOverwriteTargetArtifactLabel: false
        allowPurgeData: false
        allowSkipTilesWithMissingPrerequisites: false
        allowTakeOver: false

  - job: AddUserToWorkspaceProduction
    steps:
     - task: Workspaces-AddUser@1
       inputs:
         pbiConnection: 'Power BI'
         workspace: '$(WorkspaceName)'
         userUpn: '$(UserEmail)'
         permission: 'Admin'