trigger:
- push

pool:
  vmImage: 'windows-latest'

  jobs:
  - job: Build
  steps:
  - checkout: self 

stages:
- stage: FirstStage
  jobs:
  - job: createapipeline
    steps:
    - task: DeploymentPipelines-Create@1
      inputs:
        pbiConnection: 'Power BI new'
        displayName: 'Create a new pipeline'

  - job: Assignaworkspacetoadeploymentpipeline
    steps:
    - task: DeploymentPipelines-Assign@1
      inputs:
        pbiConnection: 'Power BI new'
        pipeline: 'TEST'
        stageOrder: '0'
        workspace: 'Pipeline'

  - job: AddaUserToaPipelineStage
    steps:
    - task: DeploymentPipelines-AddUser@1
      inputs:
        pbiConnection: 'Power BI new'
        pipeline: 'TEST'
        userUpn: 'anastasia.lahoiskaya@gmail.com'

- stage: TestStage
  jobs:
  - job: DeployToTest
    steps:
    - task: DeploymentPipelines-Deploy@1
      inputs:
        pbiConnection: 'Power BI new'
        pipeline: 'TEST'
        stageOrder: 'Test'
        deployType: 'All'
        waitForCompletion: true
        createNewWS: true
        newWsName: '$(PipelineName)[Test]'
        allowCreateArtifact: true
        allowOverwriteArtifact: true
        updateApp: false
        allowOverwriteTargetArtifactLabel: false
        allowPurgeData: false
        allowSkipTilesWithMissingPrerequisites: false
        allowTakeOver: false

  - job: AddUserToWorkspaceTest
    steps:
    - task: Workspaces-AddUser@1
      inputs:
        pbiConnection: 'Power BI new'
        workspace: 'TEST[Test]'
        userUpn: 'anastasia.lahoiskaya@gmail.com'
        permission: 'Admin'

- stage: ProductionStage
  jobs:
  - job: DeployContentToProduction
    steps:
    - task: DeploymentPipelines-Deploy@1
      inputs:
        pbiConnection: 'Power BI new'
        pipeline: 'TEST'
        stageOrder: 'Production'
        deployType: 'All'
        waitForCompletion: true
        createNewWS: true
        allowCreateArtifact: true
        allowOverwriteArtifact: true
        updateApp: false
        allowOverwriteTargetArtifactLabel: false
        allowPurgeData: false
        allowSkipTilesWithMissingPrerequisites: false
        allowTakeOver: false


  - job: AddUserToWorkspaceProduction
    steps:
     - task: Workspaces-AddUser@1
       inputs:
         pbiConnection: 'Power BI new'
         workspace: 'TEST[Prod]'
         userUpn: 'anastasia.lahoiskaya@gmail.com'
         permission: 'Admin'
