trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage: FirstStage
  jobs:
  - job: CreatePipeline
    steps:
    - script: echo Create a new pipeline in Power BI Service
      displayName: 'Create a new pipeline'

  - job: AssignWorkspace
    steps:
    - script: echo Assign a workspace to a pipeline stage
      displayName: 'Assign a workspace to a pipeline stage'

  - job: AddUserToPipeline
    steps:
    - script: echo Add a user to a pipeline
      displayName: 'Add a user to a pipeline'

- stage: TestStage
  jobs:
  - job: DeployContentToTest
    steps:
    - script: echo Deploy content to the Test stage
      displayName: 'Deploy content to the Test stage'

  - job: AddUserToWorkspaceTest
    steps:
    - script: echo Add a user to a workspace (Test)
      displayName: 'Add a user to a workspace (Test)'

- stage: ProductionStage
  jobs:
  - job: DeployContentToProduction
    steps:
    - script: echo Deploy content to the Production stage
      displayName: 'Deploy content to the Production stage'

  - job: AddUserToWorkspaceProduction
    steps:
    - script: echo Add a user to a workspace (Production)
      displayName: 'Add a user to a workspace (Production)'
